//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClalitWebServiceDataClient.ClalitPatientNameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0", ConfigurationName="ClalitPatientNameService.TranslationPatientNamesService")]
    public interface TranslationPatientNamesService {
        
        // CODEGEN: Generating message contract since the operation TranslationPatientNamesQuery is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clalit.org.il/TranslationPatientNames/1.0/TranslationPatientNamesQuery" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse TranslationPatientNamesQuery(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.clalit.org.il/TranslationPatientNames/1.0/TranslationPatientNamesQuery" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse> TranslationPatientNamesQueryAsync(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0")]
    public partial class TranslationPatientNamesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TranslationPatientNamesMessageInfo messageInfoField;
        
        private TranslationPatientNamesParameters parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TranslationPatientNamesMessageInfo MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
                this.RaisePropertyChanged("MessageInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TranslationPatientNamesParameters Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TranslationPatientNames.MessageInfo", Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0")]
    public partial class TranslationPatientNamesMessageInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIDField;
        
        private System.DateTime requestDatetimeField;
        
        private int requestingApplicationField;
        
        private int servingApplicationField;
        
        private int requestingSiteField;
        
        private int servingSiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime RequestDatetime {
            get {
                return this.requestDatetimeField;
            }
            set {
                this.requestDatetimeField = value;
                this.RaisePropertyChanged("RequestDatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RequestingApplication {
            get {
                return this.requestingApplicationField;
            }
            set {
                this.requestingApplicationField = value;
                this.RaisePropertyChanged("RequestingApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ServingApplication {
            get {
                return this.servingApplicationField;
            }
            set {
                this.servingApplicationField = value;
                this.RaisePropertyChanged("ServingApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RequestingSite {
            get {
                return this.requestingSiteField;
            }
            set {
                this.requestingSiteField = value;
                this.RaisePropertyChanged("RequestingSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ServingSite {
            get {
                return this.servingSiteField;
            }
            set {
                this.servingSiteField = value;
                this.RaisePropertyChanged("ServingSite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TranslationPatientNames.Results", Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0")]
    public partial class TranslationPatientNamesResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long patientIDField;
        
        private bool patientIDFieldSpecified;
        
        private string lastNameField;
        
        private string lastNameEngField;
        
        private int lastNameEng_TranslationTypeField;
        
        private bool lastNameEng_TranslationTypeFieldSpecified;
        
        private string firstNameField;
        
        private string firstNameEngField;
        
        private int firstNameEng_TranslationTypeField;
        
        private bool firstNameEng_TranslationTypeFieldSpecified;
        
        private string fatherNameField;
        
        private string fatherNameEngField;
        
        private int fatherNameEng_TranslationTypeField;
        
        private bool fatherNameEng_TranslationTypeFieldSpecified;
        
        private string motherNameField;
        
        private string motherNameEngField;
        
        private int motherNameEng_TranslationTypeField;
        
        private bool motherNameEng_TranslationTypeFieldSpecified;
        
        private string previousFamilyNameField;
        
        private int genderIDField;
        
        private bool genderIDFieldSpecified;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("PatientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientIDSpecified {
            get {
                return this.patientIDFieldSpecified;
            }
            set {
                this.patientIDFieldSpecified = value;
                this.RaisePropertyChanged("PatientIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastNameEng {
            get {
                return this.lastNameEngField;
            }
            set {
                this.lastNameEngField = value;
                this.RaisePropertyChanged("LastNameEng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int LastNameEng_TranslationType {
            get {
                return this.lastNameEng_TranslationTypeField;
            }
            set {
                this.lastNameEng_TranslationTypeField = value;
                this.RaisePropertyChanged("LastNameEng_TranslationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastNameEng_TranslationTypeSpecified {
            get {
                return this.lastNameEng_TranslationTypeFieldSpecified;
            }
            set {
                this.lastNameEng_TranslationTypeFieldSpecified = value;
                this.RaisePropertyChanged("LastNameEng_TranslationTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstNameEng {
            get {
                return this.firstNameEngField;
            }
            set {
                this.firstNameEngField = value;
                this.RaisePropertyChanged("FirstNameEng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int FirstNameEng_TranslationType {
            get {
                return this.firstNameEng_TranslationTypeField;
            }
            set {
                this.firstNameEng_TranslationTypeField = value;
                this.RaisePropertyChanged("FirstNameEng_TranslationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstNameEng_TranslationTypeSpecified {
            get {
                return this.firstNameEng_TranslationTypeFieldSpecified;
            }
            set {
                this.firstNameEng_TranslationTypeFieldSpecified = value;
                this.RaisePropertyChanged("FirstNameEng_TranslationTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
                this.RaisePropertyChanged("FatherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FatherNameEng {
            get {
                return this.fatherNameEngField;
            }
            set {
                this.fatherNameEngField = value;
                this.RaisePropertyChanged("FatherNameEng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int FatherNameEng_TranslationType {
            get {
                return this.fatherNameEng_TranslationTypeField;
            }
            set {
                this.fatherNameEng_TranslationTypeField = value;
                this.RaisePropertyChanged("FatherNameEng_TranslationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FatherNameEng_TranslationTypeSpecified {
            get {
                return this.fatherNameEng_TranslationTypeFieldSpecified;
            }
            set {
                this.fatherNameEng_TranslationTypeFieldSpecified = value;
                this.RaisePropertyChanged("FatherNameEng_TranslationTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MotherName {
            get {
                return this.motherNameField;
            }
            set {
                this.motherNameField = value;
                this.RaisePropertyChanged("MotherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MotherNameEng {
            get {
                return this.motherNameEngField;
            }
            set {
                this.motherNameEngField = value;
                this.RaisePropertyChanged("MotherNameEng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int MotherNameEng_TranslationType {
            get {
                return this.motherNameEng_TranslationTypeField;
            }
            set {
                this.motherNameEng_TranslationTypeField = value;
                this.RaisePropertyChanged("MotherNameEng_TranslationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MotherNameEng_TranslationTypeSpecified {
            get {
                return this.motherNameEng_TranslationTypeFieldSpecified;
            }
            set {
                this.motherNameEng_TranslationTypeFieldSpecified = value;
                this.RaisePropertyChanged("MotherNameEng_TranslationTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PreviousFamilyName {
            get {
                return this.previousFamilyNameField;
            }
            set {
                this.previousFamilyNameField = value;
                this.RaisePropertyChanged("PreviousFamilyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int GenderID {
            get {
                return this.genderIDField;
            }
            set {
                this.genderIDField = value;
                this.RaisePropertyChanged("GenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderIDSpecified {
            get {
                return this.genderIDFieldSpecified;
            }
            set {
                this.genderIDFieldSpecified = value;
                this.RaisePropertyChanged("GenderIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("BirthDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TranslationPatientNames.Parameters", Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0")]
    public partial class TranslationPatientNamesParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long patientIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PatientID {
            get {
                return this.patientIDField;
            }
            set {
                this.patientIDField = value;
                this.RaisePropertyChanged("PatientID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0")]
    public partial class TranslationPatientNamesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string statusDescriptionField;
        
        private TranslationPatientNamesMessageInfo messageInfoField;
        
        private string[] dataSourcesField;
        
        private TranslationPatientNamesResults resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TranslationPatientNamesMessageInfo MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
                this.RaisePropertyChanged("MessageInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataSource", IsNullable=false)]
        public string[] DataSources {
            get {
                return this.dataSourcesField;
            }
            set {
                this.dataSourcesField = value;
                this.RaisePropertyChanged("DataSources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TranslationPatientNamesResults Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslationPatientNamesQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0", Order=0)]
        public ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesRequest TranslationPatientNamesRequest;
        
        public TranslationPatientNamesQueryRequest() {
        }
        
        public TranslationPatientNamesQueryRequest(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesRequest TranslationPatientNamesRequest) {
            this.TranslationPatientNamesRequest = TranslationPatientNamesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslationPatientNamesQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.clalit.org.il/TranslationPatientNames/1.0", Order=0)]
        public ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesResponse TranslationPatientNamesResponse;
        
        public TranslationPatientNamesQueryResponse() {
        }
        
        public TranslationPatientNamesQueryResponse(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesResponse TranslationPatientNamesResponse) {
            this.TranslationPatientNamesResponse = TranslationPatientNamesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TranslationPatientNamesServiceChannel : ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslationPatientNamesServiceClient : System.ServiceModel.ClientBase<ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService>, ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService {
        
        public TranslationPatientNamesServiceClient() {
        }
        
        public TranslationPatientNamesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationPatientNamesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationPatientNamesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationPatientNamesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService.TranslationPatientNamesQuery(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest request) {
            return base.Channel.TranslationPatientNamesQuery(request);
        }
        
        public ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesResponse TranslationPatientNamesQuery(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesRequest TranslationPatientNamesRequest) {
            ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest inValue = new ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest();
            inValue.TranslationPatientNamesRequest = TranslationPatientNamesRequest;
            ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse retVal = ((ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService)(this)).TranslationPatientNamesQuery(inValue);
            return retVal.TranslationPatientNamesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse> ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService.TranslationPatientNamesQueryAsync(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest request) {
            return base.Channel.TranslationPatientNamesQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryResponse> TranslationPatientNamesQueryAsync(ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesRequest TranslationPatientNamesRequest) {
            ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest inValue = new ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesQueryRequest();
            inValue.TranslationPatientNamesRequest = TranslationPatientNamesRequest;
            return ((ClalitWebServiceDataClient.ClalitPatientNameService.TranslationPatientNamesService)(this)).TranslationPatientNamesQueryAsync(inValue);
        }
    }
}
