//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShebaPatientInfoSource.ShebaDemographicsProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSource", Namespace="http://tempuri.org")]
    public enum DataSource : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOTH = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryType", Namespace="http://tempuri.org")]
    public enum QueryType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImutNames = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImutDOB = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImutID = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ens_Messagebody", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShebaPatientInfoSource.ShebaDemographicsProxy.Ens_Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShebaPatientInfoSource.ShebaDemographicsProxy.Output))]
    public partial class Ens_Messagebody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ens_Response", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShebaPatientInfoSource.ShebaDemographicsProxy.Output))]
    public partial class Ens_Response : ShebaPatientInfoSource.ShebaDemographicsProxy.Ens_Messagebody {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Output", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class Output : ShebaPatientInfoSource.ShebaDemographicsProxy.Ens_Response {
        
        private string StatusField;
        
        private System.Nullable<ShebaPatientInfoSource.ShebaDemographicsProxy.Output.DataSourceType> DataSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShebaPatientInfoSource.ShebaDemographicsProxy.PatientDetails PatDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<ShebaPatientInfoSource.ShebaDemographicsProxy.Output.DataSourceType> DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((this.DataSourceField.Equals(value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.PatientDetails PatDetails {
            get {
                return this.PatDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PatDetailsField, value) != true)) {
                    this.PatDetailsField = value;
                    this.RaisePropertyChanged("PatDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ErrMessage {
            get {
                return this.ErrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMessageField, value) != true)) {
                    this.ErrMessageField = value;
                    this.RaisePropertyChanged("ErrMessage");
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Output.DataSourceType", Namespace="http://tempuri.org")]
        public enum DataSourceType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MF = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MOIN = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDetails", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class PatientDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> errstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> patientidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string familynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fathernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> numchildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> immigyearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthcntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> birthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> zipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> citycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hometelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string worktelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string engfnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string engpnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string citynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kupacodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> milidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> deathdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> baitnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baitletterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> diranoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> newzipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> pobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string updatedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobile1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobile2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ushort> pobcitycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pobcitynameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> errstatus {
            get {
                return this.errstatusField;
            }
            set {
                if ((this.errstatusField.Equals(value) != true)) {
                    this.errstatusField = value;
                    this.RaisePropertyChanged("errstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> patientid {
            get {
                return this.patientidField;
            }
            set {
                if ((this.patientidField.Equals(value) != true)) {
                    this.patientidField = value;
                    this.RaisePropertyChanged("patientid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string familyname {
            get {
                return this.familynameField;
            }
            set {
                if ((object.ReferenceEquals(this.familynameField, value) != true)) {
                    this.familynameField = value;
                    this.RaisePropertyChanged("familyname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string fathername {
            get {
                return this.fathernameField;
            }
            set {
                if ((object.ReferenceEquals(this.fathernameField, value) != true)) {
                    this.fathernameField = value;
                    this.RaisePropertyChanged("fathername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                if ((object.ReferenceEquals(this.statField, value) != true)) {
                    this.statField = value;
                    this.RaisePropertyChanged("stat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<ushort> numchildren {
            get {
                return this.numchildrenField;
            }
            set {
                if ((this.numchildrenField.Equals(value) != true)) {
                    this.numchildrenField = value;
                    this.RaisePropertyChanged("numchildren");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.nationalityField, value) != true)) {
                    this.nationalityField = value;
                    this.RaisePropertyChanged("nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<ushort> immigyear {
            get {
                return this.immigyearField;
            }
            set {
                if ((this.immigyearField.Equals(value) != true)) {
                    this.immigyearField = value;
                    this.RaisePropertyChanged("immigyear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string birthcntry {
            get {
                return this.birthcntryField;
            }
            set {
                if ((object.ReferenceEquals(this.birthcntryField, value) != true)) {
                    this.birthcntryField = value;
                    this.RaisePropertyChanged("birthcntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<uint> birthdate {
            get {
                return this.birthdateField;
            }
            set {
                if ((this.birthdateField.Equals(value) != true)) {
                    this.birthdateField = value;
                    this.RaisePropertyChanged("birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<uint> zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                if ((this.zipcodeField.Equals(value) != true)) {
                    this.zipcodeField = value;
                    this.RaisePropertyChanged("zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<ushort> citycode {
            get {
                return this.citycodeField;
            }
            set {
                if ((this.citycodeField.Equals(value) != true)) {
                    this.citycodeField = value;
                    this.RaisePropertyChanged("citycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string hometel {
            get {
                return this.hometelField;
            }
            set {
                if ((object.ReferenceEquals(this.hometelField, value) != true)) {
                    this.hometelField = value;
                    this.RaisePropertyChanged("hometel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string worktel {
            get {
                return this.worktelField;
            }
            set {
                if ((object.ReferenceEquals(this.worktelField, value) != true)) {
                    this.worktelField = value;
                    this.RaisePropertyChanged("worktel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string engfname {
            get {
                return this.engfnameField;
            }
            set {
                if ((object.ReferenceEquals(this.engfnameField, value) != true)) {
                    this.engfnameField = value;
                    this.RaisePropertyChanged("engfname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string engpname {
            get {
                return this.engpnameField;
            }
            set {
                if ((object.ReferenceEquals(this.engpnameField, value) != true)) {
                    this.engpnameField = value;
                    this.RaisePropertyChanged("engpname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string cityname {
            get {
                return this.citynameField;
            }
            set {
                if ((object.ReferenceEquals(this.citynameField, value) != true)) {
                    this.citynameField = value;
                    this.RaisePropertyChanged("cityname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string kupacode {
            get {
                return this.kupacodeField;
            }
            set {
                if ((object.ReferenceEquals(this.kupacodeField, value) != true)) {
                    this.kupacodeField = value;
                    this.RaisePropertyChanged("kupacode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<uint> milid {
            get {
                return this.milidField;
            }
            set {
                if ((this.milidField.Equals(value) != true)) {
                    this.milidField = value;
                    this.RaisePropertyChanged("milid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string faxno {
            get {
                return this.faxnoField;
            }
            set {
                if ((object.ReferenceEquals(this.faxnoField, value) != true)) {
                    this.faxnoField = value;
                    this.RaisePropertyChanged("faxno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<uint> deathdate {
            get {
                return this.deathdateField;
            }
            set {
                if ((this.deathdateField.Equals(value) != true)) {
                    this.deathdateField = value;
                    this.RaisePropertyChanged("deathdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string streetname {
            get {
                return this.streetnameField;
            }
            set {
                if ((object.ReferenceEquals(this.streetnameField, value) != true)) {
                    this.streetnameField = value;
                    this.RaisePropertyChanged("streetname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public System.Nullable<ushort> baitno {
            get {
                return this.baitnoField;
            }
            set {
                if ((this.baitnoField.Equals(value) != true)) {
                    this.baitnoField = value;
                    this.RaisePropertyChanged("baitno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string baitletter {
            get {
                return this.baitletterField;
            }
            set {
                if ((object.ReferenceEquals(this.baitletterField, value) != true)) {
                    this.baitletterField = value;
                    this.RaisePropertyChanged("baitletter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string entno {
            get {
                return this.entnoField;
            }
            set {
                if ((object.ReferenceEquals(this.entnoField, value) != true)) {
                    this.entnoField = value;
                    this.RaisePropertyChanged("entno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public System.Nullable<ushort> dirano {
            get {
                return this.diranoField;
            }
            set {
                if ((this.diranoField.Equals(value) != true)) {
                    this.diranoField = value;
                    this.RaisePropertyChanged("dirano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public System.Nullable<uint> newzipcode {
            get {
                return this.newzipcodeField;
            }
            set {
                if ((this.newzipcodeField.Equals(value) != true)) {
                    this.newzipcodeField = value;
                    this.RaisePropertyChanged("newzipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public System.Nullable<uint> pob {
            get {
                return this.pobField;
            }
            set {
                if ((this.pobField.Equals(value) != true)) {
                    this.pobField = value;
                    this.RaisePropertyChanged("pob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string updatedate {
            get {
                return this.updatedateField;
            }
            set {
                if ((object.ReferenceEquals(this.updatedateField, value) != true)) {
                    this.updatedateField = value;
                    this.RaisePropertyChanged("updatedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public string mobile1 {
            get {
                return this.mobile1Field;
            }
            set {
                if ((object.ReferenceEquals(this.mobile1Field, value) != true)) {
                    this.mobile1Field = value;
                    this.RaisePropertyChanged("mobile1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string mobile2 {
            get {
                return this.mobile2Field;
            }
            set {
                if ((object.ReferenceEquals(this.mobile2Field, value) != true)) {
                    this.mobile2Field = value;
                    this.RaisePropertyChanged("mobile2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public System.Nullable<ushort> pobcitycode {
            get {
                return this.pobcitycodeField;
            }
            set {
                if ((this.pobcitycodeField.Equals(value) != true)) {
                    this.pobcitycodeField = value;
                    this.RaisePropertyChanged("pobcitycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string pobcityname {
            get {
                return this.pobcitynameField;
            }
            set {
                if ((object.ReferenceEquals(this.pobcitynameField, value) != true)) {
                    this.pobcitynameField = value;
                    this.RaisePropertyChanged("pobcityname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Sheba.CoreInterfaces.WS.DemogBoth.ServiceSoap", Namespace="http://tempuri.org", ConfigurationName="ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap")]
    public interface ShebaCoreInterfacesWSDemogBothServiceSoap {
        
        // CODEGEN: Generating message contract since element name SendingApp from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sheba.CoreInterfaces.BS.Demog.InputSecure.GetPatientDetails", ReplyAction="*")]
        ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse GetPatientDetails(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sheba.CoreInterfaces.BS.Demog.InputSecure.GetPatientDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse> GetPatientDetailsAsync(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientDetails", Namespace="http://tempuri.org", Order=0)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequestBody Body;
        
        public GetPatientDetailsRequest() {
        }
        
        public GetPatientDetailsRequest(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetPatientDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendingApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.DataSource DataSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.QueryType QueryType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long PatientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BirthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AppUserName;
        
        public GetPatientDetailsRequestBody() {
        }
        
        public GetPatientDetailsRequestBody(string SendingApp, ShebaPatientInfoSource.ShebaDemographicsProxy.DataSource DataSource, ShebaPatientInfoSource.ShebaDemographicsProxy.QueryType QueryType, long PatientID, string FirstName, string LastName, string BirthDate, string AppUserName) {
            this.SendingApp = SendingApp;
            this.DataSource = DataSource;
            this.QueryType = QueryType;
            this.PatientID = PatientID;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.BirthDate = BirthDate;
            this.AppUserName = AppUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientDetailsResponse", Namespace="http://tempuri.org", Order=0)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponseBody Body;
        
        public GetPatientDetailsResponse() {
        }
        
        public GetPatientDetailsResponse(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetPatientDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShebaPatientInfoSource.ShebaDemographicsProxy.Output GetPatientDetailsResult;
        
        public GetPatientDetailsResponseBody() {
        }
        
        public GetPatientDetailsResponseBody(ShebaPatientInfoSource.ShebaDemographicsProxy.Output GetPatientDetailsResult) {
            this.GetPatientDetailsResult = GetPatientDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShebaCoreInterfacesWSDemogBothServiceSoapChannel : ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShebaCoreInterfacesWSDemogBothServiceSoapClient : System.ServiceModel.ClientBase<ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap>, ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap {
        
        public ShebaCoreInterfacesWSDemogBothServiceSoapClient() {
        }
        
        public ShebaCoreInterfacesWSDemogBothServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShebaCoreInterfacesWSDemogBothServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShebaCoreInterfacesWSDemogBothServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShebaCoreInterfacesWSDemogBothServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap.GetPatientDetails(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest request) {
            return base.Channel.GetPatientDetails(request);
        }
        
        public ShebaPatientInfoSource.ShebaDemographicsProxy.Output GetPatientDetails(string SendingApp, ShebaPatientInfoSource.ShebaDemographicsProxy.DataSource DataSource, ShebaPatientInfoSource.ShebaDemographicsProxy.QueryType QueryType, long PatientID, string FirstName, string LastName, string BirthDate, string AppUserName) {
            ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest inValue = new ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest();
            inValue.Body = new ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequestBody();
            inValue.Body.SendingApp = SendingApp;
            inValue.Body.DataSource = DataSource;
            inValue.Body.QueryType = QueryType;
            inValue.Body.PatientID = PatientID;
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.BirthDate = BirthDate;
            inValue.Body.AppUserName = AppUserName;
            ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse retVal = ((ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap)(this)).GetPatientDetails(inValue);
            return retVal.Body.GetPatientDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse> ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap.GetPatientDetailsAsync(ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest request) {
            return base.Channel.GetPatientDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsResponse> GetPatientDetailsAsync(string SendingApp, ShebaPatientInfoSource.ShebaDemographicsProxy.DataSource DataSource, ShebaPatientInfoSource.ShebaDemographicsProxy.QueryType QueryType, long PatientID, string FirstName, string LastName, string BirthDate, string AppUserName) {
            ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest inValue = new ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequest();
            inValue.Body = new ShebaPatientInfoSource.ShebaDemographicsProxy.GetPatientDetailsRequestBody();
            inValue.Body.SendingApp = SendingApp;
            inValue.Body.DataSource = DataSource;
            inValue.Body.QueryType = QueryType;
            inValue.Body.PatientID = PatientID;
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.BirthDate = BirthDate;
            inValue.Body.AppUserName = AppUserName;
            return ((ShebaPatientInfoSource.ShebaDemographicsProxy.ShebaCoreInterfacesWSDemogBothServiceSoap)(this)).GetPatientDetailsAsync(inValue);
        }
    }
}
