//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeumitWebServiceDataClient.LeumitPatientInformationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mw300ir.org/mw300ir/", ConfigurationName="LeumitPatientInformationService.mw300irPortType")]
    public interface mw300irPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="MW300IR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationResponse mw300irOperation(LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="MW300IR", ReplyAction="*")]
        System.Threading.Tasks.Task<LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationResponse> mw300irOperationAsync(LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.shellWiz.com/shellWizHeader/v1.0")]
    public partial class ShellWizHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string envField;
        
        private string indField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string env {
            get {
                return this.envField;
            }
            set {
                this.envField = value;
                this.RaisePropertyChanged("env");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ind {
            get {
                return this.indField;
            }
            set {
                this.indField = value;
                this.RaisePropertyChanged("ind");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mw300ir.org/mw300ir/")]
    public partial class MW300D : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal sUGIDField;
        
        private decimal nUMBIDField;
        
        private decimal sTATUSField;
        
        private decimal bTDATEField;
        
        private string fNAMEField;
        
        private string sNAMEField;
        
        private decimal aGEField;
        
        private string gENDERField;
        
        private decimal tYPEINSURField;
        
        private string nAMEINSURField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal SUGID {
            get {
                return this.sUGIDField;
            }
            set {
                this.sUGIDField = value;
                this.RaisePropertyChanged("SUGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal NUMBID {
            get {
                return this.nUMBIDField;
            }
            set {
                this.nUMBIDField = value;
                this.RaisePropertyChanged("NUMBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal BTDATE {
            get {
                return this.bTDATEField;
            }
            set {
                this.bTDATEField = value;
                this.RaisePropertyChanged("BTDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FNAME {
            get {
                return this.fNAMEField;
            }
            set {
                this.fNAMEField = value;
                this.RaisePropertyChanged("FNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SNAME {
            get {
                return this.sNAMEField;
            }
            set {
                this.sNAMEField = value;
                this.RaisePropertyChanged("SNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal AGE {
            get {
                return this.aGEField;
            }
            set {
                this.aGEField = value;
                this.RaisePropertyChanged("AGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GENDER {
            get {
                return this.gENDERField;
            }
            set {
                this.gENDERField = value;
                this.RaisePropertyChanged("GENDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal TYPEINSUR {
            get {
                return this.tYPEINSURField;
            }
            set {
                this.tYPEINSURField = value;
                this.RaisePropertyChanged("TYPEINSUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string NAMEINSUR {
            get {
                return this.nAMEINSURField;
            }
            set {
                this.nAMEINSURField = value;
                this.RaisePropertyChanged("NAMEINSUR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mw300ir.org/mw300ir/")]
    public partial class PRMGLOBAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pGL_ORIGINField;
        
        private string pGL_OPCODEField;
        
        private decimal pGL_RCField;
        
        private string pGL_MESSAGEField;
        
        private decimal pGL_SEVERITYField;
        
        private string pGL_PGM_CLASSField;
        
        private string pGL_MDL_MTHDField;
        
        private string pGL_USERField;
        
        private string pGL_GROUPField;
        
        private string pGL_IPADDRField;
        
        private string pGL_ENCUSRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PGL_ORIGIN {
            get {
                return this.pGL_ORIGINField;
            }
            set {
                this.pGL_ORIGINField = value;
                this.RaisePropertyChanged("PGL_ORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PGL_OPCODE {
            get {
                return this.pGL_OPCODEField;
            }
            set {
                this.pGL_OPCODEField = value;
                this.RaisePropertyChanged("PGL_OPCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal PGL_RC {
            get {
                return this.pGL_RCField;
            }
            set {
                this.pGL_RCField = value;
                this.RaisePropertyChanged("PGL_RC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PGL_MESSAGE {
            get {
                return this.pGL_MESSAGEField;
            }
            set {
                this.pGL_MESSAGEField = value;
                this.RaisePropertyChanged("PGL_MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal PGL_SEVERITY {
            get {
                return this.pGL_SEVERITYField;
            }
            set {
                this.pGL_SEVERITYField = value;
                this.RaisePropertyChanged("PGL_SEVERITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PGL_PGM_CLASS {
            get {
                return this.pGL_PGM_CLASSField;
            }
            set {
                this.pGL_PGM_CLASSField = value;
                this.RaisePropertyChanged("PGL_PGM_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PGL_MDL_MTHD {
            get {
                return this.pGL_MDL_MTHDField;
            }
            set {
                this.pGL_MDL_MTHDField = value;
                this.RaisePropertyChanged("PGL_MDL_MTHD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PGL_USER {
            get {
                return this.pGL_USERField;
            }
            set {
                this.pGL_USERField = value;
                this.RaisePropertyChanged("PGL_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PGL_GROUP {
            get {
                return this.pGL_GROUPField;
            }
            set {
                this.pGL_GROUPField = value;
                this.RaisePropertyChanged("PGL_GROUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PGL_IPADDR {
            get {
                return this.pGL_IPADDRField;
            }
            set {
                this.pGL_IPADDRField = value;
                this.RaisePropertyChanged("PGL_IPADDR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PGL_ENCUSR {
            get {
                return this.pGL_ENCUSRField;
            }
            set {
                this.pGL_ENCUSRField = value;
                this.RaisePropertyChanged("PGL_ENCUSR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mw300ir.org/mw300ir/")]
    public partial class mw300irMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PRMGLOBAL pRMGLOBALField;
        
        private MW300D mW300DField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PRMGLOBAL PRMGLOBAL {
            get {
                return this.pRMGLOBALField;
            }
            set {
                this.pRMGLOBALField = value;
                this.RaisePropertyChanged("PRMGLOBAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MW300D MW300D {
            get {
                return this.mW300DField;
            }
            set {
                this.mW300DField = value;
                this.RaisePropertyChanged("MW300D");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mw300irOperationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.shellWiz.com/shellWizHeader/v1.0")]
        public LeumitWebServiceDataClient.LeumitPatientInformationService.ShellWizHeader ShellWizHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mw300ir.org/mw300ir/", Order=0)]
        public LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irMessageRequest mw300irMessageRequest;
        
        public mw300irOperationRequest() {
        }
        
        public mw300irOperationRequest(LeumitWebServiceDataClient.LeumitPatientInformationService.ShellWizHeader ShellWizHeader, LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irMessageRequest mw300irMessageRequest) {
            this.ShellWizHeader = ShellWizHeader;
            this.mw300irMessageRequest = mw300irMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mw300irMessageResponse", WrapperNamespace="http://www.mw300ir.org/mw300ir/", IsWrapped=true)]
    public partial class mw300irOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mw300ir.org/mw300ir/", Order=0)]
        public int wsrc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mw300ir.org/mw300ir/", Order=1)]
        public string wsrcmsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mw300ir.org/mw300ir/", Order=2)]
        public LeumitWebServiceDataClient.LeumitPatientInformationService.PRMGLOBAL PRMGLOBAL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mw300ir.org/mw300ir/", Order=3)]
        public LeumitWebServiceDataClient.LeumitPatientInformationService.MW300D MW300D;
        
        public mw300irOperationResponse() {
        }
        
        public mw300irOperationResponse(int wsrc, string wsrcmsg, LeumitWebServiceDataClient.LeumitPatientInformationService.PRMGLOBAL PRMGLOBAL, LeumitWebServiceDataClient.LeumitPatientInformationService.MW300D MW300D) {
            this.wsrc = wsrc;
            this.wsrcmsg = wsrcmsg;
            this.PRMGLOBAL = PRMGLOBAL;
            this.MW300D = MW300D;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mw300irPortTypeChannel : LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mw300irPortTypeClient : System.ServiceModel.ClientBase<LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irPortType>, LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irPortType {
        
        public mw300irPortTypeClient() {
        }
        
        public mw300irPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mw300irPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mw300irPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mw300irPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationResponse LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irPortType.mw300irOperation(LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest request) {
            return base.Channel.mw300irOperation(request);
        }
        
        public int mw300irOperation(LeumitWebServiceDataClient.LeumitPatientInformationService.ShellWizHeader ShellWizHeader, LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irMessageRequest mw300irMessageRequest, out string wsrcmsg, out LeumitWebServiceDataClient.LeumitPatientInformationService.PRMGLOBAL PRMGLOBAL, out LeumitWebServiceDataClient.LeumitPatientInformationService.MW300D MW300D) {
            LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest inValue = new LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest();
            inValue.ShellWizHeader = ShellWizHeader;
            inValue.mw300irMessageRequest = mw300irMessageRequest;
            LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationResponse retVal = ((LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irPortType)(this)).mw300irOperation(inValue);
            wsrcmsg = retVal.wsrcmsg;
            PRMGLOBAL = retVal.PRMGLOBAL;
            MW300D = retVal.MW300D;
            return retVal.wsrc;
        }
        
        public System.Threading.Tasks.Task<LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationResponse> mw300irOperationAsync(LeumitWebServiceDataClient.LeumitPatientInformationService.mw300irOperationRequest request) {
            return base.Channel.mw300irOperationAsync(request);
        }
    }
}
